/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package campuslandserp;

import java.util.ArrayList;

/**
 *
 * @author camper
 */
public class create_camper extends javax.swing.JFrame {
    arrays Campers = new arrays();
    /**
     * Creates new form create
     */
    public create_camper() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titulo = new javax.swing.JLabel();
        nombres = new javax.swing.JTextField();
        NombresLabel = new javax.swing.JLabel();
        ApellidosLabel = new javax.swing.JLabel();
        apellidos = new javax.swing.JTextField();
        DireccionLabel = new javax.swing.JLabel();
        direccion = new javax.swing.JTextField();
        IdentificacionLabel = new javax.swing.JLabel();
        identificacion = new javax.swing.JTextField();
        enviar = new javax.swing.JButton();
        AcudienteLabel = new javax.swing.JLabel();
        acudiente = new javax.swing.JTextField();
        CelularLabel = new javax.swing.JLabel();
        TelefonoLabel = new javax.swing.JLabel();
        celular = new javax.swing.JTextField();
        telefono = new javax.swing.JTextField();
        cancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        titulo.setBackground(new java.awt.Color(255, 255, 255));
        titulo.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        titulo.setForeground(new java.awt.Color(102, 51, 255));
        titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo.setText("Ingresar nuevo Camper");

        NombresLabel.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        NombresLabel.setText("Nombres");

        ApellidosLabel.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        ApellidosLabel.setText("Apellidos");

        DireccionLabel.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        DireccionLabel.setText("Dirección");

        IdentificacionLabel.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        IdentificacionLabel.setText("Número de identificación");

        enviar.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        enviar.setText("Confirmar");
        enviar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                enviarMouseClicked(evt);
            }
        });

        AcudienteLabel.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        AcudienteLabel.setText("Acudiente");

        CelularLabel.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        CelularLabel.setText("Telefono celular");

        TelefonoLabel.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        TelefonoLabel.setText("Telefono fijo");

        cancel.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        cancel.setText("Cancelar");
        cancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cancelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(180, 180, 180)
                .addComponent(titulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(180, 180, 180))
            .addGroup(layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(IdentificacionLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(DireccionLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ApellidosLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(NombresLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(AcudienteLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(CelularLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TelefonoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nombres)
                    .addComponent(apellidos)
                    .addComponent(direccion)
                    .addComponent(identificacion)
                    .addComponent(acudiente)
                    .addComponent(celular)
                    .addComponent(telefono))
                .addGap(90, 90, 90))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(231, Short.MAX_VALUE)
                .addComponent(enviar)
                .addGap(28, 28, 28)
                .addComponent(cancel)
                .addGap(241, 241, 241))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(IdentificacionLabel)
                    .addComponent(identificacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NombresLabel)
                    .addComponent(nombres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ApellidosLabel)
                    .addComponent(apellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DireccionLabel)
                    .addComponent(direccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AcudienteLabel)
                    .addComponent(acudiente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CelularLabel)
                    .addComponent(celular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TelefonoLabel)
                    .addComponent(telefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancel)
                    .addComponent(enviar))
                .addGap(36, 36, 36))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelMouseClicked
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_cancelMouseClicked

    private void enviarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_enviarMouseClicked
        // TODO add your handling code here:
        
        String new_idenficacion = identificacion.getText();
        String new_nombres = nombres.getText();
        String new_apellidos = apellidos.getText();
        String new_direccion = direccion.getText();
        String new_acudiente = acudiente.getText();
        String new_celular = celular.getText();
        String new_telefono = telefono.getText();
        
        camper Camper = new camper(new_idenficacion,new_nombres, new_apellidos, new_direccion, new_acudiente, new_celular, new_telefono);
        
        Campers.listadd(Camper);
        System.out.println(Campers);
        System.out.println(Campers.getSize());
        dispose();
    }//GEN-LAST:event_enviarMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AcudienteLabel;
    private javax.swing.JLabel ApellidosLabel;
    private javax.swing.JLabel CelularLabel;
    private javax.swing.JLabel DireccionLabel;
    private javax.swing.JLabel IdentificacionLabel;
    private javax.swing.JLabel NombresLabel;
    private javax.swing.JLabel TelefonoLabel;
    public javax.swing.JTextField acudiente;
    public javax.swing.JTextField apellidos;
    private javax.swing.JButton cancel;
    public javax.swing.JTextField celular;
    public javax.swing.JTextField direccion;
    private javax.swing.JButton enviar;
    public javax.swing.JTextField identificacion;
    public javax.swing.JTextField nombres;
    public javax.swing.JTextField telefono;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables

    private void add(camper Camper1) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
